//------------------------------------------------------------------------------
// <auto-generated>
//     VSTO host item. Visual Studio may regenerate this file.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Cat
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(
        global::System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes;

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
            "Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
            "Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        internal Microsoft.Office.Interop.PowerPoint.Application Application;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisAddIn(global::Microsoft.Office.Tools.Factory factory,
                         global::System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Microsoft.Office.Interop.PowerPoint.Application>(
                typeof(Microsoft.Office.Interop.PowerPoint.Application), "Application");
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            InitializeControls();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization()
        {
            InternalStartup();
            OnStartup();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings()
        {
            BeginInitialization();
            EndInitialization();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization()
        {
            BeginInit();
            CustomTaskPanes.BeginInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization()
        {
            CustomTaskPanes.EndInit();
            EndInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls()
        {
            CustomTaskPanes = Globals.Factory.CreateCustomTaskPaneCollection(
                null, null, "CustomTaskPanes", "CustomTaskPanes", this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown()
        {
            CustomTaskPanes.Dispose();
            base.OnShutdown();
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    internal sealed partial class Globals
    {
        private Globals() { }

        private static ThisAddIn _thisAddIn;
        private static global::Microsoft.Office.Tools.Factory _factory;

        internal static ThisAddIn ThisAddIn
        {
            get { return _thisAddIn; }
            set
            {
                if (_thisAddIn == null) _thisAddIn = value;
                else throw new global::System.NotSupportedException();
            }
        }

        internal static global::Microsoft.Office.Tools.Factory Factory
        {
            get { return _factory; }
            set
            {
                if (_factory == null) _factory = value;
                else throw new global::System.NotSupportedException();
            }
        }
    }
}
